Readjust the testing docs to run phoenix on ocis backend with no ldap setup
owncloud/phoenix pull request #4040
Opened 2020-09-03 05:04 UTC by jasson99

## Description
This PR adjusts the testing document to run phoenix on ocis backend without ldap setup.

## Related Issue
- Fixes https://github.com/owncloud/phoenix/issues/4034

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2020-09-07 11:57 UTC, individual-it approved these changes

2020-09-07 14:06 UTC, kulmann requested changes

2020-09-07 14:06 UTC, kulmann commented on package.json
> +    "ocis:mac": "yarn run build-ocis; REVA_STORAGE_OWNCLOUD_REDIS_ADDR='localhost:6379' REVA_OIDC_ISSUER='https://host.docker.internal:9200' KONNECTD_IDENTIFIER_REGISTRATION_CONF='./tests/acceptance/
The env var for the oidc issuer is not `REVA_OIDC_ISSUER` but `PROXY_OIDC_ISSUER`.

Also `KONNECTD_INSECURE='true'` is needed for local runs as well.

2020-09-11 08:04 UTC, kulmann approved these changes
👍

2020-09-11 08:57 UTC, merged